export const GET_ALL_SUBGROUP = "GET_ALL_SUBGROUP";
export const GET_ACTUAL_SUBGROUP = "GET_ACTUAL_SUBGROUP";
export const CHECK_SUBGROUP = "CHECK_SUBGROUP";
export const CHANGE_GRAPHIC = "CHANGE_GRAPHIC";

export const REVIEW_PRODUCT = "REVIEW_PRODUCT";
export const REVIEW_PRODUCT_SUBGROUP = "REVIEW_PRODUCT_SUBGROUP";
export const PRODUCT_INDEX = "PRODUCT_INDEX";
export const STEP = "STEP";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const RESET_REVIEW_SUBGROUP = "RESET_REVIEW_SUBGROUP";
export const RESET_SELECTED_SUBGROUP = "RESET_SELECTED_SUBGROUP";
