export const GET_CONDITIONS = "GET_CONDITIONS";

// subgroup
export const GET_ALL_SUBGROUP = "GET_ALL_SUBGROUP";
export const GET_ACTUAL_SUBGROUP = "GET_ACTUAL_SUBGROUP";
export const CHECK_SUBGROUP = "CHECK_SUBGROUP";
export const CHANGE_GRAPHIC = "CHANGE_GRAPHIC";

// Product
export const REVIEW_PRODUCT = "REVIEW_PRODUCT";
export const REJECTED_PRODUCT = "REJECTED_PRODUCT";
export const ACCEPTED_PRODUCT = "ACCEPTED_PRODUCT";
export const REVIEW_PRODUCT_SUBGROUP = "REVIEW_PRODUCT_SUBGROUP";
export const PRODUCT_INDEX = "PRODUCT_INDEX";
export const STEP = "STEP";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CHANGE_STATE_MESSAGE = "CHANGE_STATE_MESSAGE";
export const RESET_REVIEW_SUBGROUP = "RESET_REVIEW_SUBGROUP";
export const RESET_SELECTED_SUBGROUP = "RESET_SELECTED_SUBGROUP";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGN_OFF = "SIGN_OFF";

// Teacher
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_ERROR = "COURSE_ERROR";
export const GET_COURSES = "GET_COURSES";
export const GET_ACTUAL_COURSE = "GET_ACTUAL_COURSE";
export const GET_STUDENTS = "GET_STUDENTS";

export const GET_ALL_PRACTICES_SUCCESS = "GET_ALL_PRACTICES_SUCCESS";
export const GET_ALL_PRACTICES_ERROR = "GET_ALL_PRACTICES_ERROR";

export const GET_GROUPS_PRACTICE_1 = "GET_GROUPS_PRACTICE_1";
export const GET_GROUPS_PRACTICE_2 = "GET_GROUPS_PRACTICE_2";
export const GET_GROUPS_PRACTICE_3 = "GET_GROUPS_PRACTICE_3";

export const LOADING = "LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_ERROR = "LOADING_ERROR";
